Analytics cron
GSA-TTS/identity-idva-monitoring pull request #269
Opened 2023-11-16 22:08 UTC by nathan-moore-97

2023-11-16 22:34 UTC, dzaslavskiy requested changes

2023-11-16 22:34 UTC, dzaslavskiy commented on .github/workflows/deploy-cron.yaml
> +        run: cf push --var ENVIRONMENT=${{ steps.cf-setup.outputs.target-environment }} --strategy rolling
This step is a duplicate of the one below

2023-11-16 22:34 UTC, dzaslavskiy commented on cron/manifest.yaml
> +      GDRIVE_APP_HOST: "idva-gdrive-((ENVIRONMENT)).apps.internal"
This change has already been commited

2023-11-16 22:53 UTC, nathan-moore-97 commented on .github/workflows/deploy-cron.yaml
> +        run: cf push --var ENVIRONMENT=${{ steps.cf-setup.outputs.target-environment }} --strategy rolling
I dont understand what you mean here

2023-11-16 22:55 UTC, nathan-moore-97 commented on .github/workflows/deploy-cron.yaml
Missing working directory

2023-11-16 22:56 UTC, nathan-moore-97 commented on .github/workflows/deploy-cron.yaml
> +        run: cf push --var ENVIRONMENT=${{ steps.cf-setup.outputs.target-environment }} --strategy rolling
Oh, I see

2023-11-16 22:57 UTC, nathan-moore-97 commented on cron/manifest.yaml
> +      GDRIVE_APP_HOST: "idva-gdrive-((ENVIRONMENT)).apps.internal"
I dont know why its here again, and not sure what I should do to fix it

2023-11-16 23:07 UTC, dzaslavskiy commented on cron/manifest.yaml
> +      GDRIVE_APP_HOST: "idva-gdrive-((ENVIRONMENT)).apps.internal"
same as we did before

2023-11-17 16:27 UTC, dzaslavskiy approved these changes

2023-11-17 16:28 UTC, merged